spring:
  application:
    name: educationinusa-service

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8083

#JWT security
educationinusa:
  app:
    jwtSecret: EducationInUSA@2098
    jwtExpirationMs: 86400000
